package me.abdullah.pvp.modes;

import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemFlag;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.PlayerInventory;
import org.bukkit.inventory.meta.ItemMeta;

import me.abdullah.pvp.a.main.Main;
import me.abdullah.pvp.mysql.PVPStats;
import me.abdullah.pvp.utils.PlayersSettings;

public class AutoKit {
	public static void Enabled(Player p)
	{
    PlayerInventory pInv = p.getInventory();

     pInv.remove(Settings.Item(p));
     pInv.remove(Spectator.Spectator(p));
     pInv.remove(new ItemStack(Material.SUGAR));
     pInv.remove(new ItemStack(Material.REDSTONE_COMPARATOR));
     if (p.hasPermission("ffa.vip")) {
	    ItemStack swordvip = new ItemStack(Material.STONE_SWORD);
	    ItemMeta swordvipVIP = swordvip.getItemMeta();
	    swordvipVIP.setDisplayName(Main.color("&6Sword"));
	    swordvipVIP.spigot().setUnbreakable(true);
	    swordvipVIP.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
	    swordvip.setItemMeta(swordvipVIP);
	    swordvip.addEnchantment(Enchantment.DAMAGE_ALL, 2);
	    ItemStack bowvip = new ItemStack(Material.BOW);
	    ItemMeta bowvipmeta = bowvip.getItemMeta();
	    bowvipmeta.setDisplayName(Main.color("&6Bow"));       
	    bowvipmeta.spigot().setUnbreakable(true);
	    bowvipmeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
	    bowvip.setItemMeta(bowvipmeta);
	    bowvip.addEnchantment(Enchantment.ARROW_DAMAGE, 1);
	    ItemStack helmetvip = new ItemStack(Material.IRON_HELMET);
	    ItemMeta helmetvipmeta = helmetvip.getItemMeta();
	    helmetvipmeta.setDisplayName(Main.color("&6Helmet"));
	    helmetvipmeta.spigot().setUnbreakable(true);
	    helmetvipmeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
	    helmetvip.setItemMeta(helmetvipmeta);
	    helmetvip.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
	    ItemStack chestplatevip = new ItemStack(Material.IRON_CHESTPLATE);
	    ItemMeta chestplatevipmeta = chestplatevip.getItemMeta();
	    chestplatevipmeta.setDisplayName(Main.color("&6Chestplate"));
	    chestplatevipmeta.spigot().setUnbreakable(true);
	    chestplatevipmeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
	    chestplatevip.setItemMeta(chestplatevipmeta);
	    chestplatevip.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
	    ItemStack leggingsvip = new ItemStack(Material.IRON_LEGGINGS);
	    ItemMeta leggingsvipmeta = leggingsvip.getItemMeta();
	    leggingsvipmeta.setDisplayName(Main.color("&6Leggings"));
	    leggingsvipmeta.spigot().setUnbreakable(true);
	    leggingsvipmeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
	    leggingsvip.setItemMeta(leggingsvipmeta);
	    leggingsvip.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
	    ItemStack Bootvip = new ItemStack(Material.IRON_BOOTS);
	    ItemMeta Bootvipmeta = Bootvip.getItemMeta();
	    Bootvipmeta.setDisplayName(Main.color("&6Boot"));
	    Bootvipmeta.spigot().setUnbreakable(true);
	    Bootvipmeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
	    Bootvip.setItemMeta(Bootvipmeta);
	    Bootvip.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
	    ItemStack Rodvip = new ItemStack(Material.FISHING_ROD);
	    ItemMeta Rodvipmeta = Rodvip.getItemMeta();
	    Rodvipmeta.setDisplayName(Main.color("&6Rod"));
	    Rodvipmeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
	    Rodvipmeta.spigot().setUnbreakable(true);
	    Rodvip.setItemMeta(Rodvipmeta);
	    pInv.setItem(0, swordvip);
	    pInv.setItem(1, Rodvip);
	    pInv.setItem(2, bowvip);
	    pInv.setItem(8, new ItemStack(Material.ARROW, 5));
	    pInv.setHelmet(helmetvip);
	    pInv.setChestplate(chestplatevip);
	    pInv.setLeggings(leggingsvip);
	    pInv.setBoots(Bootvip);			
    } else if (p.hasPermission("ffa.mvp")) {
        pInv.remove(Settings.Item(p));
        pInv.remove(Spectator.Spectator(p));
        pInv.remove(new ItemStack(Material.SUGAR));
        pInv.remove(new ItemStack(Material.REDSTONE_COMPARATOR));
        ItemStack swordmvp = new ItemStack(Material.IRON_SWORD);
        ItemMeta swordmvpmeta = swordmvp.getItemMeta();
        swordmvpmeta.setDisplayName(Main.color("&bSword"));
        swordmvpmeta.spigot().setUnbreakable(true);
        swordmvpmeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
        swordmvp.setItemMeta(swordmvpmeta);
        swordmvp.addEnchantment(Enchantment.DAMAGE_ALL, 1);
        ItemStack bowmvp = new ItemStack(Material.BOW);
        ItemMeta bowmvpmeta = bowmvp.getItemMeta();
        bowmvpmeta.setDisplayName(Main.color("&bBow"));       
        bowmvpmeta.spigot().setUnbreakable(true);
        bowmvpmeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
        bowmvp.setItemMeta(bowmvpmeta);
        bowmvp.addEnchantment(Enchantment.ARROW_DAMAGE, 2);
        ItemStack helmetmvp = new ItemStack(Material.IRON_HELMET);
        ItemMeta helmetmvpmeta = helmetmvp.getItemMeta();
        helmetmvpmeta.setDisplayName(Main.color("&bHelmet"));
        helmetmvpmeta.spigot().setUnbreakable(true);
        helmetmvpmeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
        helmetmvp.setItemMeta(helmetmvpmeta);
        helmetmvp.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
        ItemStack chestplatemvp = new ItemStack(Material.IRON_CHESTPLATE);
        ItemMeta chestplatemvpmeta = chestplatemvp.getItemMeta();
        chestplatemvpmeta.setDisplayName(Main.color("&bChestplate"));
        chestplatemvpmeta.spigot().setUnbreakable(true);
        chestplatemvpmeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
        chestplatemvp.setItemMeta(chestplatemvpmeta);
        chestplatemvp.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 2);
        ItemStack leggingsmvp = new ItemStack(Material.IRON_LEGGINGS);
        ItemMeta leggingsmvpmeta = leggingsmvp.getItemMeta();
        leggingsmvpmeta.setDisplayName(Main.color("&bLeggings"));
        leggingsmvpmeta.spigot().setUnbreakable(true);
        leggingsmvpmeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
        leggingsmvp.setItemMeta(leggingsmvpmeta);
        leggingsmvp.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
        ItemStack Bootmvp = new ItemStack(Material.DIAMOND_BOOTS);
        ItemMeta Bootmvpmeta = Bootmvp.getItemMeta();
        Bootmvpmeta.setDisplayName(Main.color("&bBoot"));
        Bootmvpmeta.spigot().setUnbreakable(true);
        Bootmvpmeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
        Bootmvp.setItemMeta(Bootmvpmeta);
        Bootmvp.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
        ItemStack Rodmvp = new ItemStack(Material.FISHING_ROD);
        ItemMeta Rodmvpmeta = Rodmvp.getItemMeta();
        Rodmvpmeta.setDisplayName(Main.color("&bRod"));
        Rodmvpmeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
        Rodmvpmeta.spigot().setUnbreakable(true);
        Rodmvp.setItemMeta(Rodmvpmeta);
        pInv.setItem(0, swordmvp);
        pInv.setItem(1, Rodmvp);
        pInv.setItem(2, bowmvp);
        pInv.setItem(7, Flint.Flint(p));        	 
        pInv.setItem(8, new ItemStack(Material.ARROW, 9));
        pInv.setHelmet(helmetmvp);
        pInv.setChestplate(chestplatemvp);
        pInv.setLeggings(leggingsmvp);
        pInv.setBoots(Bootmvp);
 	} else if (p.hasPermission("ffa.king")) {
 	
 	     pInv.remove(Settings.Item(p));
 	     pInv.remove(Spectator.Spectator(p));
 	     pInv.remove(new ItemStack(Material.SUGAR));
 	     pInv.remove(new ItemStack(Material.REDSTONE_COMPARATOR));
        ItemStack swordking = new ItemStack(Material.IRON_SWORD);
        ItemMeta swordkingmeta = swordking.getItemMeta();
        swordkingmeta.setDisplayName(Main.color("&aSword"));
        swordkingmeta.spigot().setUnbreakable(true);
        swordkingmeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
        swordking.setItemMeta(swordkingmeta);
        swordking.addEnchantment(Enchantment.DAMAGE_ALL, 1);
        ItemStack bowking = new ItemStack(Material.BOW);
        ItemMeta bowkingmeta = bowking.getItemMeta();
        bowkingmeta.setDisplayName(Main.color("&aBow"));       
        bowkingmeta.spigot().setUnbreakable(true);
        bowkingmeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
        bowking.setItemMeta(bowkingmeta);
        bowking.addEnchantment(Enchantment.ARROW_DAMAGE, 1);
        ItemStack helmetking = new ItemStack(Material.IRON_HELMET);
        ItemMeta helmetkingmeta = helmetking.getItemMeta();
        helmetkingmeta.setDisplayName(Main.color("&aHelmet"));
        helmetkingmeta.spigot().setUnbreakable(true);
        helmetkingmeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
        helmetking.setItemMeta(helmetkingmeta);
        helmetking.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
        ItemStack chestplateking = new ItemStack(Material.DIAMOND_CHESTPLATE);
        ItemMeta chestplatekingmeta = chestplateking.getItemMeta();
        chestplatekingmeta.setDisplayName(Main.color("&aChestplate"));
        chestplatekingmeta.spigot().setUnbreakable(true);
        chestplatekingmeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
        chestplateking.setItemMeta(chestplatekingmeta);
        chestplateking.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 2);
        ItemStack leggingsking = new ItemStack(Material.IRON_LEGGINGS);
        ItemMeta leggingskingmeta = leggingsking.getItemMeta();
        leggingskingmeta.setDisplayName(Main.color("&aLeggings"));
        leggingskingmeta.spigot().setUnbreakable(true);
        leggingskingmeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
        leggingsking.setItemMeta(leggingskingmeta);
        leggingsking.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
        ItemStack Bootking = new ItemStack(Material.IRON_BOOTS);
        ItemMeta Bootkingmeta = Bootking.getItemMeta();
        Bootkingmeta.setDisplayName(Main.color("&aBoot"));
        Bootkingmeta.spigot().setUnbreakable(true);
        Bootkingmeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
        Bootking.setItemMeta(Bootkingmeta);
        Bootking.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
        ItemStack Rodking = new ItemStack(Material.FISHING_ROD);
        ItemMeta Rodkingmeta = Rodking.getItemMeta();
        Rodkingmeta.setDisplayName(Main.color("&aRod"));
        Rodkingmeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
        Rodkingmeta.spigot().setUnbreakable(true);
        Rodking.setItemMeta(Rodkingmeta);
        pInv.setItem(0, swordking);
        pInv.setItem(1, Rodking);
        pInv.setItem(2, bowking);
        pInv.setItem(7, Flint.Flint(p));        	    	    
        pInv.setItem(8, new ItemStack(Material.ARROW, 12));
        pInv.setHelmet(helmetking);
        pInv.setChestplate(chestplateking);
        pInv.setLeggings(leggingsking);
        pInv.setBoots(Bootking);
	} else if (p.hasPermission("ffa.yt")) {
	
	     pInv.remove(Settings.Item(p));
	     pInv.remove(Spectator.Spectator(p));
	     pInv.remove(new ItemStack(Material.SUGAR));
	     pInv.remove(new ItemStack(Material.REDSTONE_COMPARATOR));
	        ItemStack swordYouTuber = new ItemStack(Material.IRON_SWORD);
	        ItemMeta swordYouTubermeta = swordYouTuber.getItemMeta();
	        swordYouTubermeta.setDisplayName(Main.color("&5Sword"));
	        swordYouTubermeta.spigot().setUnbreakable(true);
	        swordYouTubermeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
	        swordYouTuber.setItemMeta(swordYouTubermeta);
	        swordYouTuber.addEnchantment(Enchantment.DAMAGE_ALL, 1);
	        ItemStack bowYouTuber = new ItemStack(Material.BOW);
	        ItemMeta bowYouTubermeta = bowYouTuber.getItemMeta();
	        bowYouTubermeta.setDisplayName(Main.color("&5Bow"));       
	        bowYouTubermeta.spigot().setUnbreakable(true);
	        bowYouTubermeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
	        bowYouTuber.setItemMeta(bowYouTubermeta);
	        bowYouTuber.addEnchantment(Enchantment.ARROW_DAMAGE, 1);
	        ItemStack helmetYouTuber = new ItemStack(Material.IRON_HELMET);
	        ItemMeta helmetYouTubermeta = helmetYouTuber.getItemMeta();
	        helmetYouTubermeta.setDisplayName(Main.color("&5Helmet"));
	        helmetYouTubermeta.spigot().setUnbreakable(true);
	        helmetYouTubermeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
	        helmetYouTuber.setItemMeta(helmetYouTubermeta);
	        helmetYouTuber.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
	        ItemStack chestplateYouTuber = new ItemStack(Material.DIAMOND_CHESTPLATE);
	        ItemMeta chestplateYouTubermeta = chestplateYouTuber.getItemMeta();
	        chestplateYouTubermeta.setDisplayName(Main.color("&5Chestplate"));
	        chestplateYouTubermeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
	        chestplateYouTubermeta.spigot().setUnbreakable(true);
	        chestplateYouTuber.setItemMeta(chestplateYouTubermeta);                		        
	        ItemStack leggingsYouTuber = new ItemStack(Material.IRON_LEGGINGS);
	        ItemMeta leggingsYouTubermeta = leggingsYouTuber.getItemMeta();
	        leggingsYouTubermeta.setDisplayName(Main.color("&5Leggings"));
	        leggingsYouTubermeta.spigot().setUnbreakable(true);
	        leggingsYouTubermeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
	        leggingsYouTuber.setItemMeta(leggingsYouTubermeta);
	        leggingsYouTuber.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
	        ItemStack BootYouTuber = new ItemStack(Material.IRON_BOOTS);
	        ItemMeta BootYouTubermeta = BootYouTuber.getItemMeta();
	        BootYouTubermeta.setDisplayName(Main.color("&5Boot"));
	        BootYouTubermeta.spigot().setUnbreakable(true);
	        BootYouTubermeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
	        BootYouTuber.setItemMeta(BootYouTubermeta);
	        BootYouTuber.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
	        ItemStack RodYouTuber = new ItemStack(Material.FISHING_ROD);
	        ItemMeta RodYouTubermeta = RodYouTuber.getItemMeta();
	        RodYouTubermeta.setDisplayName(Main.color("&5Rod"));
	        RodYouTubermeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);	
	        RodYouTubermeta.spigot().setUnbreakable(true);
	        RodYouTuber.setItemMeta(RodYouTubermeta);
	        pInv.setItem(0, swordYouTuber);
	        pInv.setItem(1, RodYouTuber);
	        pInv.setItem(2, bowYouTuber);
            pInv.setItem(7, Flint.Flint(p));        	 
	        pInv.setItem(8, new ItemStack(Material.ARROW, 12));
	        pInv.setHelmet(helmetYouTuber);
	        pInv.setChestplate(chestplateYouTuber);
	        pInv.setLeggings(leggingsYouTuber);
	        pInv.setBoots(BootYouTuber);
		} else if (PVPStats.getPoints(p.getName()) >= 1300 && p.hasPermission("ffa.goldkit")) {
		
		     pInv.remove(Settings.Item(p));
		     pInv.remove(Spectator.Spectator(p));
		     pInv.remove(new ItemStack(Material.SUGAR));
		     pInv.remove(new ItemStack(Material.REDSTONE_COMPARATOR));
            ItemStack sword2 = new ItemStack(Material.STONE_SWORD);
            ItemMeta meta = sword2.getItemMeta();
            meta.setDisplayName(Main.color("&eSword"));
            meta.spigot().setUnbreakable(true);
            meta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
            sword2.setItemMeta(meta);
            sword2.addEnchantment(Enchantment.DAMAGE_ALL, 2);
            ItemStack bow2 = new ItemStack(Material.BOW);
            ItemMeta bowmeta = bow2.getItemMeta();
            bowmeta.setDisplayName(Main.color("&eBow"));
            bowmeta.spigot().setUnbreakable(true);
            bowmeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
            bow2.setItemMeta(bowmeta);
            bow2.addEnchantment(Enchantment.ARROW_DAMAGE, 1);
            ItemStack arrow = new ItemStack(Material.ARROW, 10);
            ItemMeta arrowmeta2 = arrow.getItemMeta();
            arrowmeta2.setDisplayName(Main.color("&eArrow"));
            arrowmeta2.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
            arrow.setItemMeta(arrowmeta2);
            ItemStack helmet2 = new ItemStack(Material.IRON_HELMET);
            ItemMeta helmetmeta2 = helmet2.getItemMeta();
            helmetmeta2.setDisplayName(Main.color("&eHelmet"));
            helmetmeta2.spigot().setUnbreakable(true);
            helmetmeta2.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
            helmet2.setItemMeta(helmetmeta2);
            helmet2.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
            ItemStack chestplate = new ItemStack(Material.IRON_CHESTPLATE);
            ItemMeta chestplatemeta = chestplate.getItemMeta();
            chestplatemeta.setDisplayName(Main.color("&eChestplate"));
            chestplatemeta.spigot().setUnbreakable(true);
            chestplatemeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
            chestplate.setItemMeta(chestplatemeta);
            chestplate.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
            ItemStack leggings = new ItemStack(Material.IRON_LEGGINGS);
            ItemMeta leggingsmeta = chestplate.getItemMeta();
            leggingsmeta.setDisplayName(Main.color("&eLeggings"));
            leggingsmeta.spigot().setUnbreakable(true);
            leggingsmeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
            leggings.setItemMeta(leggingsmeta);
            leggings.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
            ItemStack Boot2 = new ItemStack(Material.IRON_BOOTS);
            ItemMeta Bootmeta2 = Boot2.getItemMeta();
            Bootmeta2.setDisplayName(Main.color("&eBoot"));
            Bootmeta2.spigot().setUnbreakable(true);
            Bootmeta2.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
            Boot2.setItemMeta(Bootmeta2);
            Boot2.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
            ItemStack Rod2 = new ItemStack(Material.FISHING_ROD);
            ItemMeta Rodmeta = Rod2.getItemMeta();
            Rodmeta.setDisplayName(Main.color("&eRod"));
            Rodmeta.spigot().setUnbreakable(true);
            Rodmeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
            Rod2.setItemMeta(Rodmeta);
            pInv.setItem(0, sword2);
            pInv.setItem(1, Rod2);
            pInv.setItem(2, bow2);
            pInv.setItem(7, Flint.Flint(p));		        	            
            pInv.setItem(8, arrow);
            pInv.setHelmet(helmet2);
            pInv.setChestplate(chestplate);
            pInv.setLeggings(leggings);
            pInv.setBoots(Boot2);
        } else if (PVPStats.getPoints(p.getName()) >= 2600 && p.hasPermission("ffa.diamondkit")) {
       
            pInv.remove(Settings.Item(p));
            pInv.remove(Spectator.Spectator(p));
            pInv.remove(new ItemStack(Material.SUGAR));
            pInv.remove(new ItemStack(Material.REDSTONE_COMPARATOR));
        	Bukkit.dispatchCommand(Bukkit.getConsoleSender(), "lp user " + p.getName() +  " permission set " + " ffa.diamondkit");		
            ItemStack sword2 = new ItemStack(Material.IRON_SWORD);
            ItemMeta meta = sword2.getItemMeta();
            meta.setDisplayName(Main.color("&e&lSword"));
            meta.spigot().setUnbreakable(true);
            sword2.setItemMeta(meta);
            meta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
            sword2.addEnchantment(Enchantment.DAMAGE_ALL, 2);
            ItemStack bow2 = new ItemStack(Material.BOW);
            ItemMeta bowmeta = bow2.getItemMeta();
            bowmeta.setDisplayName(Main.color("&e&lBow"));
            bowmeta.spigot().setUnbreakable(true);
            bow2.setItemMeta(bowmeta);
            bowmeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
            bow2.addEnchantment(Enchantment.ARROW_DAMAGE, 2);
            ItemStack arrow = new ItemStack(Material.ARROW, 15);
            ItemMeta arrowmeta2 = arrow.getItemMeta();
            arrowmeta2.setDisplayName(Main.color("&e&lArrow"));
            arrow.setItemMeta(arrowmeta2);
            ItemStack helmet2 = new ItemStack(Material.IRON_HELMET);
            ItemMeta helmetmeta2 = helmet2.getItemMeta();
            helmetmeta2.setDisplayName(Main.color("&e&lHelmet"));
            helmetmeta2.spigot().setUnbreakable(true);
            helmetmeta2.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
            helmet2.setItemMeta(helmetmeta2);
            helmet2.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
            ItemStack chestplate = new ItemStack(Material.IRON_CHESTPLATE);
            ItemMeta chestplatemeta = chestplate.getItemMeta();
            chestplatemeta.setDisplayName(Main.color("&e&lChestplate"));
            chestplatemeta.spigot().setUnbreakable(true);
            chestplatemeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
            chestplate.setItemMeta(chestplatemeta);
            chestplate.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 2);
            ItemStack leggings = new ItemStack(Material.IRON_LEGGINGS);
            ItemMeta leggingsmeta = chestplate.getItemMeta();
            leggingsmeta.setDisplayName(Main.color("&e&lLeggings"));
            leggingsmeta.spigot().setUnbreakable(true);
            leggingsmeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
            leggings.setItemMeta(leggingsmeta);
            leggings.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 2);
            ItemStack Boot2 = new ItemStack(Material.IRON_BOOTS);
            ItemMeta Bootmeta2 = Boot2.getItemMeta();
            Bootmeta2.setDisplayName(Main.color("&e&lBoot"));
            Bootmeta2.spigot().setUnbreakable(true);
            Bootmeta2.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
            Boot2.setItemMeta(Bootmeta2);
            Boot2.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
            ItemStack Rod2 = new ItemStack(Material.FISHING_ROD);
            ItemMeta Rodmeta = Rod2.getItemMeta();
            Rodmeta.setDisplayName(Main.color("&e&lRod"));
            Rodmeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
            Rodmeta.spigot().setUnbreakable(true);
            Rod2.setItemMeta(Rodmeta);
            pInv.setItem(0, sword2);
            pInv.setItem(1, Rod2);
            pInv.setItem(2, bow2);
            pInv.setItem(7, Flint.Flint(p));		        	            
            pInv.setItem(8, arrow);
            pInv.setHelmet(helmet2);
            pInv.setChestplate(chestplate);
            pInv.setLeggings(leggings);
            pInv.setBoots(Boot2);
        } else {
       
            pInv.remove(Settings.Item(p));
            pInv.remove(Spectator.Spectator(p));
            pInv.remove(new ItemStack(Material.SUGAR));
            pInv.remove(new ItemStack(Material.REDSTONE_COMPARATOR));
            ItemStack swordMember = new ItemStack(Material.STONE_SWORD);
            ItemMeta swordMembermeta = swordMember.getItemMeta();
            swordMembermeta.setDisplayName(Main.color("&9Sword"));
            swordMembermeta.spigot().setUnbreakable(true);
            swordMembermeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
            swordMember.setItemMeta(swordMembermeta);
            swordMember.addEnchantment(Enchantment.DAMAGE_ALL, 1);
            ItemStack bowMember = new ItemStack(Material.BOW);
            ItemMeta bowMembermeta = bowMember.getItemMeta();
            bowMembermeta.setDisplayName(Main.color("&9Bow"));       
            bowMembermeta.spigot().setUnbreakable(true);
            bowMembermeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
            bowMember.setItemMeta(bowMembermeta);
            ItemStack helmetMember = new ItemStack(Material.IRON_HELMET);
            ItemMeta helmetMembermeta = helmetMember.getItemMeta();
            helmetMembermeta.setDisplayName(Main.color("&9Helmet"));
            helmetMembermeta.spigot().setUnbreakable(true);
            helmetMembermeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
            helmetMember.setItemMeta(helmetMembermeta);		        
            ItemStack chestplateMember = new ItemStack(Material.IRON_CHESTPLATE);
            ItemMeta chestplateMembermeta = chestplateMember.getItemMeta();
            chestplateMembermeta.setDisplayName(Main.color("&9Chestplate"));
            chestplateMembermeta.spigot().setUnbreakable(true);
            chestplateMembermeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
            chestplateMember.setItemMeta(chestplateMembermeta);
            chestplateMember.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
            ItemStack leggingsMember = new ItemStack(Material.IRON_LEGGINGS);
            ItemMeta leggingsMembermeta = leggingsMember.getItemMeta();
            leggingsMembermeta.setDisplayName(Main.color("&9Leggings"));
            leggingsMembermeta.spigot().setUnbreakable(true);
            leggingsMembermeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
            leggingsMember.setItemMeta(leggingsMembermeta);
            leggingsMember.addEnchantment(Enchantment.PROTECTION_ENVIRONMENTAL, 1);
            ItemStack BootMember = new ItemStack(Material.IRON_BOOTS);
            ItemMeta BootMembermeta = BootMember.getItemMeta();
            BootMembermeta.setDisplayName(Main.color("&9Boot"));
            BootMembermeta.spigot().setUnbreakable(true);
            BootMembermeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
            BootMember.setItemMeta(BootMembermeta);
            ItemStack RodMember = new ItemStack(Material.FISHING_ROD);
            ItemMeta RodMembermeta = RodMember.getItemMeta();
            RodMembermeta.setDisplayName(Main.color("&9Rod"));
            RodMembermeta.addItemFlags(ItemFlag.HIDE_UNBREAKABLE);
            RodMembermeta.spigot().setUnbreakable(true);
            RodMember.setItemMeta(RodMembermeta);
            pInv.setItem(0, swordMember);
            pInv.setItem(1, RodMember);
            pInv.setItem(2, bowMember);
            pInv.setItem(7, Flint.Flint(p));        	    
            pInv.setItem(8, new ItemStack(Material.ARROW, 3));
            pInv.setHelmet(helmetMember);
            pInv.setChestplate(chestplateMember);
            pInv.setLeggings(leggingsMember);
            pInv.setBoots(BootMember);
        }
   }
  }